In [2]:
import numpy as np

In [16]:
""" Example to understand the approach of statistical ops like max()
    Ref : https://realpython.com/numpy-max-maximum/#using-max

    Each row represents one student, and each column contains the scores on a particular test.
    So column 0 contains all the student scores for the first test, column 1 contains the scores
    for the second test, and so on. Here’s the n_scores array:
"""
# rows are students(student1, student2... student8), columns are test-names(test1, test2... test5)
n_scores = np.array([
       [63, 72, 75, 51, 83],
       [44, 53, 57, 56, 48],
       [71, 77, 82, 91, 76],
       [67, 56, 82, 33, 74],
       [64, 76, 72, 63, 76],
       [47, 56, 49, 53, 42],
       [91, 93, 90, 88, 96],
       [61, 56, 77, 74, 74],
])  
np.shape(n_scores)

(8, 5)

In [11]:
# Both the below  approaches are same since n_scores is a ndarray
print(n_scores.max())
print(np.max(n_scores))

96
96


In [12]:
# Get the maximum score for each test
n_scores.max(axis=0)

array([91, 93, 90, 91, 96])

In [13]:
# Get the maximum score for each student
n_scores.max(axis=1)

array([83, 57, 91, 82, 76, 56, 96, 77])

In [28]:
# 3D array of size 4x2x3 
a = np.array(
    [
        [[3,7,6],[1,5,2]],
        [[1,2,4],[7,2,9]],
        [[1,0,0],[5,4,3]],
        [[8,1,4],[2,7,8]]
    ])
a

array([[[3, 7, 6],
        [1, 5, 2]],

       [[1, 2, 4],
        [7, 2, 9]],

       [[1, 0, 0],
        [5, 4, 3]],

       [[8, 1, 4],
        [2, 7, 8]]])

In [6]:
a[0], a[0][0], a[0][0][0]

(array([[3, 7, 6],
        [1, 5, 2]]),
 array([3, 7, 6]),
 3)

In [7]:
np.max(a, axis=0)

array([[8, 7, 6],
       [7, 7, 9]])

In [21]:
np.max(a, axis=1)

array([[3, 7, 6],
       [7, 2, 9],
       [5, 4, 3],
       [8, 7, 8]])

In [9]:
np.max(a, axis=2)

array([[7, 5],
       [4, 9],
       [1, 5],
       [8, 8]])

In [26]:
a

array([[[3, 7, 6],
        [1, 5, 2]],

       [[1, 2, 4],
        [7, 2, 9]],

       [[1, 0, 0],
        [5, 4, 3]],

       [[8, 1, 4],
        [2, 7, 8]]])

In [24]:
np.sum(a)

92

In [25]:
np.sum(a, axis=0)

array([[13, 10, 14],
       [15, 18, 22]])

In [29]:
np.sum(a, axis=1)

array([[ 4, 12,  8],
       [ 8,  4, 13],
       [ 6,  4,  3],
       [10,  8, 12]])

In [30]:
np.sum(a, axis=2)

array([[16,  8],
       [ 7, 18],
       [ 1, 12],
       [13, 17]])